# Start with an Ubuntu 22.04 ros-humble image
FROM osrf/ros:humble-desktop-full

# Set shell to bash and prevent dpkg frontend dialog
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

# Source the ROS 2 setup.bash in bashrc for interactive shells
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    git \
    python3-colcon-common-extensions \
    python3-rosdep \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-twist-mux \
    ros-humble-teleop-twist-keyboard \
    ros-humble-joy \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-gazebo-ros2-control \
    ros-humble-controller-manager \
    nano && \
    apt-get clean && rm -rf /var/lib/apt/lists/* \
    apt-get install ros-humble-gazebo-tools

# Entry point to ensure container remains running
CMD ["bash"]